company:
  name: Louis Bank
  main-branch-name: Main Branch
  main-branch-address: Accra
  account-names-prefix: LB
  account-password-suffix: 123
  minimum-allowed-account-balance: 1.00
  initial-account-balance: 0.00
  send-emails: true
  admin-contact: +233542411666
server:
  port: 8081
  servlet:
    context-path: /app
  error:
    include-message: always
spring:
  devtools:
    add-properties: false
  flyway:
    enabled: true
    schemas:    - banking
    installed-by: Louis Gamor
  datasource:
    username: 
    password: 
    url: jdbc:mysql://127.0.0.1:3306/banking?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
  main:
    allow-bean-definition-overriding: true
  mail:
    host: <email-domain-host>
    username: <email-address>
    password: <email-domain-password>
    port: 993
    sender: <email-address>
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
centrifugo:
  api-key: <centrifugo-api-key>
  channelAccount: Accounts
  channelTransaction: Transactions
  method: publish
  secret: <centrifugo-secret>
  url: <centrifugo-url>
  websocket: <centrifugo-websocket-url>
